"""
Stage 8: Close the loop in Jira
"""
from typing import Optional
from utils.logger import get_logger
from utils.jira_client import JiraClient

logger = get_logger('stage_8_jira_close')

class JiraCloseStage:
    def __init__(self, jira_client: JiraClient):
        self.jira = jira_client
    
    def run(self, issue_key: str, test_status: str, deployment_url: str, bug_report_content: str) -> Optional[bool]:
        """
        Transition Jira story to final state (Done or Bug Reported)
        and add comment with results
        Returns: True if successful
        """
        try:
            logger.info(f"Closing issue {issue_key} with status {test_status}")
            
            # Determine final state
            if test_status == 'passed':
                final_state = 'Done'
                comment = f"""✅ Pipeline completed successfully!

**Deployment URL:** {deployment_url}

All acceptance criteria passed. The application is ready for production.

**Generated by:** AI Pipeline
"""
            else:
                final_state = 'Bug Reported'
                comment = f"""⚠️ Pipeline completed with issues

**Deployment URL:** {deployment_url}

Some acceptance criteria failed. See bug report below:

{bug_report_content}

**Generated by:** AI Pipeline
"""
            
            # Transition issue
            success = self.jira.transition_issue(issue_key, final_state)
            
            if success:
                # Add comment
                self.jira.add_comment(issue_key, comment)
                logger.info(f"Successfully closed {issue_key} with state {final_state}")
                return True
            else:
                logger.error(f"Failed to transition {issue_key} to {final_state}")
                return False
        
        except Exception as e:
            logger.error(f"Error in Jira close stage: {e}", exc_info=True)
            return False

def stage_8_jira_close(issue_key: str, test_status: str, deployment_url: str, bug_report_content: str):
    """Execute Stage 8"""
    jira = JiraClient()
    closer = JiraCloseStage(jira)
    return closer.run(issue_key, test_status, deployment_url, bug_report_content)
