"""
Stage 4: Push code to GitHub and create PR
"""
import os
import subprocess
import requests
from typing import Optional, Dict
from utils.logger import get_logger
from utils.config import GITHUB_TOKEN, GITHUB_REPO_OWNER, GITHUB_REPO_NAME

logger = get_logger('stage_4_github')

class GitHubStage:
    def __init__(self, app_dir: str, issue_key: str):
        self.app_dir = app_dir
        self.issue_key = issue_key
        self.branch_name = f"feature/{issue_key.lower()}-automated"
    
    def run(self) -> Optional[Dict]:
        """
        Initialize git repo, create branch, commit, push, and open PR
        Returns: Dictionary with PR info
        """
        try:
            logger.info(f"Starting GitHub stage for {self.issue_key}")
            
            # Initialize git if not already done
            if not os.path.exists(os.path.join(self.app_dir, '.git')):
                logger.info("Initializing git repository")
                subprocess.run(['git', 'init'], cwd=self.app_dir, check=True)
                subprocess.run(['git', 'config', 'user.name', 'AI Pipeline'], cwd=self.app_dir, check=True)
                subprocess.run(['git', 'config', 'user.email', 'pipeline@example.com'], cwd=self.app_dir, check=True)

            # Create branch or switch to existing one
            existing = subprocess.run(
                ['git', 'branch', '--list', self.branch_name],
                cwd=self.app_dir, capture_output=True, text=True
            )
            if existing.stdout.strip():
                logger.info(f"Branch already exists, switching to: {self.branch_name}")
                subprocess.run(['git', 'checkout', self.branch_name], cwd=self.app_dir, check=True)
            else:
                logger.info(f"Creating branch: {self.branch_name}")
                subprocess.run(['git', 'checkout', '-b', self.branch_name], cwd=self.app_dir, check=True)

            # Add all files
            logger.info("Adding files to git")
            subprocess.run(['git', 'add', '.'], cwd=self.app_dir, check=True)

            # Commit only if there are staged changes
            diff = subprocess.run(
                ['git', 'diff', '--cached', '--quiet'],
                cwd=self.app_dir
            )
            commit_msg = f"[{self.issue_key}] Automated build by AI Pipeline"
            if diff.returncode != 0:
                logger.info(f"Committing with message: {commit_msg}")
                subprocess.run(['git', 'commit', '-m', commit_msg], cwd=self.app_dir, check=True)
            else:
                logger.info("No changes to commit")
            
            # Add remote and push
            logger.info(f"Pushing to {GITHUB_REPO_OWNER}/{GITHUB_REPO_NAME}")
            remote_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_REPO_OWNER}/{GITHUB_REPO_NAME}.git"
            
            remotes = subprocess.run(['git', 'remote'], cwd=self.app_dir, capture_output=True, text=True)
            if 'origin' in remotes.stdout.split():
                subprocess.run(['git', 'remote', 'set-url', 'origin', remote_url], cwd=self.app_dir, check=True)
            else:
                subprocess.run(['git', 'remote', 'add', 'origin', remote_url], cwd=self.app_dir, check=True)
            subprocess.run(['git', 'push', '-u', 'origin', self.branch_name], cwd=self.app_dir, check=True)
            
            # Create PR via GitHub API
            logger.info("Creating pull request")
            pr_title = f"[{self.issue_key}] Automated build by AI Pipeline"
            pr_body = f"Automated PR for {self.issue_key}\n\nGenerated by AI Pipeline"

            # Get default branch to use as base
            repo_resp = requests.get(
                f"https://api.github.com/repos/{GITHUB_REPO_OWNER}/{GITHUB_REPO_NAME}",
                headers={"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}
            )
            default_branch = repo_resp.json().get("default_branch", "main") if repo_resp.ok else "main"

            pr_resp = requests.post(
                f"https://api.github.com/repos/{GITHUB_REPO_OWNER}/{GITHUB_REPO_NAME}/pulls",
                json={"title": pr_title, "body": pr_body, "head": self.branch_name, "base": default_branch},
                headers={"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}
            )

            if pr_resp.status_code in (200, 201):
                pr_url = pr_resp.json().get("html_url", "")
                logger.info(f"PR created: {pr_url}")
                return {
                    'status': 'success',
                    'branch': self.branch_name,
                    'pr_url': pr_url,
                    'commit_message': commit_msg
                }
            elif pr_resp.status_code == 422 and "already exists" in pr_resp.text:
                # PR already open for this branch
                existing = requests.get(
                    f"https://api.github.com/repos/{GITHUB_REPO_OWNER}/{GITHUB_REPO_NAME}/pulls",
                    params={"head": f"{GITHUB_REPO_OWNER}:{self.branch_name}", "state": "open"},
                    headers={"Authorization": f"token {GITHUB_TOKEN}", "Accept": "application/vnd.github+json"}
                )
                pr_url = existing.json()[0]["html_url"] if existing.ok and existing.json() else ""
                logger.info(f"PR already exists: {pr_url}")
                return {'status': 'success', 'branch': self.branch_name, 'pr_url': pr_url, 'commit_message': commit_msg}
            else:
                logger.error(f"Failed to create PR: {pr_resp.status_code} {pr_resp.text}")
                return {
                    'status': 'partial',
                    'branch': self.branch_name,
                    'pushed': True,
                    'pr_created': False,
                    'error': pr_resp.text
                }
        
        except Exception as e:
            logger.error(f"Error in GitHub stage: {e}", exc_info=True)
            return None

def stage_4_github(app_dir: str, issue_key: str):
    """Execute Stage 4"""
    github = GitHubStage(app_dir, issue_key)
    return github.run()
